version: '3.9'

services:
  app:
    build: 
      context: .
    ports: 
      - 8080:8080

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: oluet_api_dev
    ports:
     - 5432:5432