version: '3.9'

services:
  app:
    build: 
      context: .
    environment: 
      PORT: 5000
      DATABASE_URL: postgres://dev:dev@db:5432/oluet_api_dev?sslmode=disable
    depends_on: 
      - db
    ports: 
      - 5000:5000

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: oluet_api_dev
    ports:
    - 5432:5432