version: '3.9'

services:
  app:
    build: 
      context: .
    environment: 
      PG_USER: dev
      PG_PASSWORD: dev
      PG_DBNAME: oluet_api_dev
      PG_HOST: db
      PG_PORT: 5432
      PORT: 5000
    depends_on: 
      - db
    ports: 
      - 5000:5000

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: oluet_api_dev
    ports:
    - 5432:5432