CREATE TABLE IF NOT EXISTS Juoma(
    ID serial PRIMARY KEY,
    Date DATE NOT NULL,
    ProductID INTEGER NOT NULL,
    Nimi VARCHAR (255),
    Valmistaja VARCHAR (255),
    Pullokoko VARCHAR (255),
    Hinta DOUBLE PRECISION,
    LitraHinta DOUBLE PRECISION,
    Uutuus VARCHAR (255),
    HinnastoJarjestysKoodi VARCHAR (255),
    Tyyppi VARCHAR (255),
    AlaTyyppi VARCHAR (255),
    ErityisRyhma VARCHAR (255),
    OlutTyyppi VARCHAR (255),
    ValmistusMaa VARCHAR (255),
    Alue VARCHAR (255),
    VuosiKerta VARCHAR (255),
    EtikettiMerkintoja VARCHAR (255),
    Huomautus VARCHAR (255),
    Rypaleet VARCHAR (255),
    Luonnehdinta VARCHAR (255),
    PakkausTyyppi VARCHAR (255),
    SuljentaTyyppi VARCHAR (255),
    AlkoholiProsentti VARCHAR (255),
    HapotGl VARCHAR (255),
    SokeriGl INTEGER,
    Kantavierrep DOUBLE PRECISION,
    Vari VARCHAR (255),
    Katkerot VARCHAR (255),
    Energia100ml VARCHAR (255),
    Valikoima VARCHAR (255)
)